name: "vercel-cypress"
description: "Run Cypress tests against a Vercel deployment"
branding:
  icon: "alert-circle"
  color: "green"
inputs:
  vercel-token:
    description: "Vercel API token"
    required: true
    default: ""
  project-id:
    description: "Project ID"
    required: true
    default: ""
  team-id:
    description: "Team ID (required if the project is from a team)"
    required: false
    default: ""
  options:
    description: "Cypress options"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.vercel-token }}
    - ${{ inputs.project-id }}
    - ${{ inputs.team-id }}
    - ${{ inputs.options }}
